### ISSUE TITLE
how can i install this?

### ISSUE THREAD

**Issue by zahs123** [mennthor/awkde#2]
hi, 

i have what looks like a long tail dsitibution and the current kde in scikit either oversmooths the larger area of the curve and oversmooths the tails. therefore i wish to use this method. however when i run 

pip install [--user] -e ./awkde 

i get 

string end error? how can i install this

**Comment by zgana** [comment]
@zahs123 Did you include the `[--user]` in the command?  You probably want either `pip install -e ./awkde` or `pip install --user -e ./awkde`.  The latter is appropriate for a standard installation, but if you're working in a virtualenv then you should use the former.

Also, make sure that you run this command from the directory where you ran `git clone`.  If you `cd awkde` and then run the pip command as described, it won't be looking in the right place for the needed files.

**Comment by zahs123** [comment]
hi i get this error when i use the first pip install and the second : ERROR: ./awkde is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

**Comment by zahs123** [comment]
ah right ok, i have to clone this?

**Comment by zgana** [comment]
You can install by running the following two commands:
```
git clone https://github.com/mennthor/awkde
pip install --user --editable ./awkde
```
However, if you just want the latest current code, and don't intend to modify or update it, you can just run the following command with no clone required:
```
﻿pip install --user git+https://github.com/mennthor/awkde
```

**Comment by tomasrojasc** [comment]
Hi, can you make it avaliable via pypi? I'd like to make this part of my project but in order to not have to put your repo inside mine I need to be able to pip install it

Best regards!
Tomás

**Comment by mennthor** [comment]
Hi, I just updated the backend code and the setup.py to use the current pybind11 macros.

**Comment by mennthor** [comment]
> Hi, can you make it avaliable via pypi? I'd like to make this part of my project but in order to not have to put your repo inside mine I need to be able to pip install it
> 
> Best regards! Tomás

Hi,
similar to the answer provided by @zgana above, see this SO (https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source) for how to use a direct github source in your requirements.txt for example.

I think this is not really suitable to be put on PyPi because (as you may have guessed by the long response time) I'm barely checking if something is happening here and the repo itself is not really polished and tested.
