### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by SylvainBreton** [mennthor/awkde#3]
I am really interested in using your code.

When I try to install it using the command provided in read_me I run into an error.
I'm on Mac Catalina and I want use annaconda to work on python.
Here is the error I encounter when I try to install the package :

_> pip install [--user] -e ./awkde
> ERROR: Exception:
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/packaging/requirements.py", line 98, in __init__
>     req = REQUIREMENT.parseString(requirement_string)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1947, in parseString
>     raise exc
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1937, in parseString
>     loc, tokens = self._parse(instring, 0)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 4052, in parseImpl
>     loc, exprtokens = e._parse(instring, loc, doActions)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1681, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 3798, in parseImpl
>     raise ParseException(instring, loc, self.errmsg, self)
> pip._vendor.pyparsing.ParseException: Expected stringEnd, found '['  (at char 11), (line:1, col:12)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
>     status = self.run(options, args)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 301, in run
>     wheel_cache
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 249, in populate_requirement_set
>     wheel_cache=wheel_cache
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 395, in install_req_from_line
>     parts = parse_req_from_line(name, line_source)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 346, in parse_req_from_line
>     extras = convert_extras(extras_as_string)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 77, in convert_extras
>     return Requirement("placeholder" + extras.lower()).extras
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
>     requirement_string[e.loc : e.loc + 8], e.msg
> pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[--user]'": Expected stringEnd
>_

**Comment by zgana** [comment]
The brackets around `[--user]` indicate that this is optional, depending on the desired behavior.  If you have activated an anaconda environment, I believe you should not need this argument. instead, just `pip install -e ./awkde`.  However I don't personally have experience using pip with anaconda.

See also the discussion under #2.

**Comment by SylvainBreton** [comment]
Ty this solved my issue.
(I thought that I already tried this but I must have done something wrong then)
